let arr = [];
let cart =`nav id ='cont">`;
cart += `<div id ='nav-links">`;
cart += `<div class='product'>Product Name</div>`;
cart += `<div class ='price'>Price</div>`;
cart += `<div class ='quantity'>Quantity</div>`;
cart +=`div class ='total'>Total</div>`;
cart +=`</div>`;
cart +=`</nav>`;
document.getElementById('cart').innerHTML = cart;